
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[372] =
    {   0,
        0,    0,   67,   67,   99,   98,   95,   96,   72,   86,
       94,   80,   81,   89,   88,   92,   87,   91,   90,   70,
       82,   93,   84,   77,   83,    8,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   78,   79,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   68,   67,    0,   97,   71,
       74,    0,   70,   73,   76,   85,   75,   73,   73,   73,
       62,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   36,   73,   73,   73,

       73,   73,   11,   73,   73,   73,   73,   73,   73,   73,
       24,   47,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   17,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   68,   67,   46,   48,   50,   51,   73,   73,   73,
       41,   73,   73,   45,   73,   73,   73,   31,   73,   43,

       14,   61,   73,   73,   26,   73,   73,   73,   73,   73,
       65,   73,   29,   38,   73,   73,   21,   73,   30,   25,
       73,   73,   73,    0,   73,   73,   73,   69,   73,   73,
       49,    7,   73,   40,   73,   73,   73,   42,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   30,   73,   73,   73,    0,   73,   73,
       73,   69,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   55,   73,   73,   33,   73,    5,   10,
       13,   66,   73,   18,   35,   58,   73,   56,   73,   73,

        6,   52,   15,   73,   59,   37,   60,    1,   73,   73,
       32,   69,   69,   69,   73,   73,   63,   39,   16,    2,
       28,   12,   73,   34,   57,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   69,   69,   69,   73,   73,
       73,    3,    4,   64,   19,   27,    9,   53,   73,    8,
       73,   73,   73,   22,   73,   73,   73,   73,   73,   73,
       20,   54,   73,   73,   23,   73,   73,   73,   73,   44,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,    1,   53,    1,   35,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   35,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       77,   78,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    2,    3,    2,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[380] =
    {   0,
        0,    0,   77,   80,  139, 1385, 1385, 1385,  128, 1385,
     1385, 1385, 1385, 1385, 1385, 1385, 1385,   67, 1385,   80,
     1385, 1385,   65, 1385,  102, 1385,   84,   85,   87,   88,
       99,   86,  100,  105,  125,  101,  137,  142,  144,  147,
      145,  161,  163,  176,  187, 1385, 1385,  165,  103,  150,
      194,  197,  205,  211,  219,  218,  231,  223,  234,  237,
      242,  259,  226,  283,  238,    0,  194,  108,  104,  204,
     1385,  210,  252,  239, 1385, 1385, 1385,  298,  304,  308,
      244,  315,  311,  319,  322,  312,  336,  323,  339,  340,
      344,  351,  355,  357,  361,  363,  258,  367,  365,  375,

      368,  385,  379,  382,  386,  396,  408,  402,  412,  413,
      414,  419,  425,  426,  427,  440,  429,  432,  446,  453,
      445,  457,  460,  464,  465,  472,  476,  480,  478,  486,
      482,  493,  490,  498,  506,  508,  510,  511,  513,  514,
      516,  524,  521,  526,  527,  528,  529,  531,  532,  534,
      542,  547,  549,  544,  557,  552,  560,  563,  565,  567,
      583,  586,  600,  587,  611,  622,  614,  624,  628,  630,
      632,  634,  640,  644,  645,  646,  650,  652,  657,  656,
      663,    0,  412,  660,  670,  674,  675,  676,  678,  693,
      686,  706,  700,  712,  713,  714,  718,  720,  724,  728,

      731,  734,  735,  738,  742,  746,  749,  750,  753,  752,
      756,  757,  760,  767,  768,  770,  775,  780,  781,  785,
      787,  788,  792,   87,  793,  798,  799,  833,  805,  803,
      800,  804,  845,  810,  852,  853,  855,  856,  857,  860,
      863,  867,  871,  873,  874,  877,  885,  888,  889,  900,
      893,  896,  901,  903,  906,  904,  908,  911,  907,  914,
      918,  919,  922,  925,  924,  926,  930,   79,  938,  940,
      942, 1004,  960,  941,  943,  962,  975,  976,  977, 1015,
     1016, 1023, 1028, 1385, 1030, 1031, 1029, 1034, 1035, 1045,
     1046, 1047, 1048, 1051, 1052, 1053, 1063, 1064, 1069, 1070,

     1071, 1385, 1075, 1077, 1081, 1083, 1085, 1385, 1088, 1089,
     1091,    0,    0, 1133, 1093, 1106, 1095, 1099, 1103, 1385,
     1105, 1109, 1145, 1110, 1111, 1152, 1153, 1116, 1155, 1156,
     1157, 1158, 1163, 1171, 1173,    0,    0, 1243, 1176, 1189,
     1174, 1175, 1177, 1181, 1187, 1188, 1191, 1385, 1192, 1193,
     1195, 1199, 1205, 1209, 1219, 1211, 1223, 1255, 1262, 1263,
     1265, 1385, 1266, 1267, 1270, 1277, 1278, 1283, 1284, 1291,
     1385, 1356, 1360,   86, 1364, 1368, 1372, 1376, 1380
    } ;

static const flex_int16_t yy_def[380] =
    {   0,
      371,    1,  372,  372,  371,  371,  371,  371,  373,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  374,
      371,  371,  371,  371,  371,  371,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  371,  371,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  375,  371,  373,  373,  371,
      371,  371,  374,  374,  371,  371,  371,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  375,  371,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  371,  374,  374,  374,  376,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  371,  374,  374,
      374,  377,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  371,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  371,  374,  374,  374,  374,  374,  371,  374,  374,
      374,  378,  378,  376,  374,  374,  374,  374,  374,  371,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  379,  379,  377,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  371,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  371,  374,  374,  374,  374,  374,  374,  374,  374,
        0,  371,  371,  371,  371,  371,  371,  371,  371
    } ;

static const flex_int16_t yy_nxt[1464] =
    {   0,
        6,    6,    7,    8,    9,    6,    6,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   36,   37,   38,   39,   40,
       41,   36,   42,   43,   44,   36,   45,   36,   36,   36,
       36,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   36,   57,   58,   59,   60,   61,   36,   62,
       63,   64,   36,   65,   36,   36,   36,   36,   67,    6,
       67,   67,    6,   67,   70,   70,   71,   75,   76,   74,
       71,   71,   71,   71,   71,   72,  308,   73,   73,  371,

      371,  371,  371,  371,  308,   71,   71,   71,   69,   71,
       78,   71,   69,   86,  371,  371,  371,   87,  371,   83,
      371,   88,   79,   84,   77,   94,   85,   80,   81,   95,
       89,   71,   69,   90,   82,   91,   98,   92,  371,   96,
      371,   99,   97,   71,  100,  101,  371,   93,   71,  102,
       71,   71,  371,   71,  371,  103,   71,  371,  371,  371,
      371,  371,  371,  104,  371,  371,  105,   71,  371,   71,
      106,   71,  371,  108,  113,  107,  371,  110,  371,  136,
      371,  114,   71,  109,  115,  111,  117,  116,  122,  112,
      118,  371,  371,   71,  119,  183,  123,  183,  371,  120,

       71,  126,  371,   71,  124,  127,  121,  125,  128,  371,
      137,   71,  371,  138,  371,  129,  139,   71,  130,  133,
      371,   70,   70,  131,   71,   71,  371,   70,   70,   71,
      134,  132,   71,  371,  371,  135,   81,   71,  371,  371,
       71,  371,  371,   71,   71,   71,  371,  140,   71,  371,
       71,  141,  371,  371,  371,  142,  371,  371,   71,  371,
      145,  371,  146,  143,   71,   71,  144,   72,  149,   73,
       73,  148,  147,  371,  371,  371,  103,  150,  151,  172,
       97,  371,  152,  156,  159,  153,  154,  173,  157,   71,
      155,  160,  158,  371,  174,  162,  371,  175,  371,  163,

      161,  180,  111,  371,   71,  164,  112,  371,  165,  181,
       71,  166,  167,  371,   71,  371,  168,   71,   71,  371,
      169,   71,  371,  371,  170,   71,  371,  371,   71,   71,
      371,  171,  185,  371,  371,  186,  176,  371,  371,  371,
      177,  184,   71,  178,  187,   71,   71,  371,  189,  129,
       71,  371,  179,  188,  371,  371,  192,   71,  190,  371,
      194,   71,  193,   71,  195,  191,  371,   71,  371,   71,
      371,   71,  371,   71,   71,  371,  371,  196,  371,  198,
      371,   71,  371,  371,  199,   71,  371,  197,   71,  371,
      371,   71,   71,  371,  371,  200,  371,  371,  206,  201,

      371,  371,   71,  371,  208,  202,  203,  204,   71,  205,
      209,  371,  207,  183,   71,  183,  212,  371,   71,   71,
       71,  371,  210,  371,  213,   71,  211,  371,  371,  371,
      214,   71,   71,   71,  371,   71,  216,  371,   71,  215,
      371,  371,  371,  220,  371,  224,   71,  371,  371,  217,
      218,   71,   71,  371,  221,  371,  219,  227,  371,   71,
      371,  371,  223,   71,  371,  222,   71,  226,  371,  228,
       71,   71,  371,  225,  371,  371,  229,  230,   71,  371,
      371,  231,   71,  232,   71,  371,   71,  371,   71,  371,
      371,  371,   71,  371,  236,  371,   71,  371,  234,   71,

      371,  371,  371,  233,   71,  371,  235,  237,  371,  240,
      238,  241,   71,  371,   71,  242,   71,   71,  243,   71,
       71,  371,   71,  371,  239,  371,  371,   71,  371,  371,
       71,  371,   71,   71,   71,   71,  371,   71,   71,  371,
       71,  371,  371,  371,  371,  371,  371,  371,   71,  371,
       71,  371,  371,   71,  185,   71,  371,  371,   71,  371,
      184,  186,  371,   71,  371,  187,   71,  371,  245,   71,
      248,   71,  371,   71,  249,  371,  246,  371,  371,  244,
      371,  371,  371,  191,  198,  247,  252,  371,  194,   71,
      250,  371,   71,   71,  371,  371,  200,  251,  371,  371,

      201,  371,  371,  202,  253,  254,   71,  257,  255,  371,
      258,  205,  371,  256,  371,  371,  371,   71,  260,  259,
       71,  262,  371,  211,  371,  213,  371,  268,   71,  371,
       71,  214,  371,  261,   71,  371,   71,  371,   71,  371,
       71,  217,  263,  371,  220,  371,   71,  371,  371,  371,
       71,   71,   71,  266,  264,  371,   71,  265,   71,  371,
      371,  371,   71,   71,  371,  371,   71,  371,  371,   71,
      371,  371,  371,  267,  371,  371,   71,  271,  371,  270,
       71,   71,  284,  269,   71,  371,  231,  274,  272,  371,
      371,  371,   71,  371,  371,  273,  371,  232,  371,   71,

      371,  371,  277,  285,  371,  234,   71,  275,  371,  280,
      281,  238,   71,  276,  278,  371,  283,  282,   71,   71,
       71,  371,  371,  371,   71,  279,   71,  371,  371,  371,
       71,  287,  286,  371,   71,  371,  371,   71,  371,  371,
       71,   71,  371,  371,   71,  288,  371,  291,   71,  371,
      371,  292,   71,  371,  290,   71,   71,  371,   71,   71,
      289,  371,   71,   71,  371,  371,   71,  371,  371,  371,
      371,  371,  371,   71,   71,  371,  302,  294,  296,  298,
      293,   71,  371,  371,  295,  371,   71,   71,  371,  297,
      371,   71,  371,   71,   71,  371,  371,  299,   71,   71,

      371,  300,  371,  371,   71,   71,   71,  371,  371,   71,
       71,   71,  301,  371,  371,  371,   71,  371,  371,  371,
      371,  307,  305,  304,  303,  371,  310,  311,  371,  371,
      371,  309,  306,  312,  312,  316,  312,  312,  312,  313,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      315,   71,  312,  312,  312,  312,  312,  312,   71,   71,
      371,  320,   71,   71,  371,  371,   71,  371,  371,   71,
      371,  371,  371,   71,  317,  371,  371,   71,  371,  284,
       71,  371,  371,   71,  312,  312,  371,  371,  371,  371,
      323,   71,  371,  319,   71,   71,  318,  325,  322,   71,

      371,  321,   71,  371,  371,  324,   71,   71,  371,   71,
       71,  371,   71,   71,   71,  371,  371,   71,  371,  371,
       71,  371,  371,  371,   71,  302,  371,  326,   71,  371,
       71,   71,   71,  371,  371,  371,   71,  371,  287,  371,
      371,  371,  371,  327,   71,  371,   71,   71,   71,   71,
      291,  292,  371,  371,  371,  371,  371,  371,  371,  371,
      328,  296,  371,  289,  371,  298,   71,  290,   71,  294,
      371,  295,  371,  329,  330,  371,  371,  371,  371,  331,
      371,   71,  320,   71,  371,  332,  305,  307,  371,  301,
      371,  371,  371,  303,  333,  371,  335,  306,  311,  371,

      317,  340,  371,  334,  336,  336,  371,  336,  336,  336,
      337,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,   71,   71,  336,  336,  336,  336,  336,  336,   71,
      371,  371,  339,  318,   71,   71,   71,   71,  371,  371,
       71,   71,  319,  371,  371,  371,  371,  371,  321,  371,
      371,   71,   71,   71,   71,  336,  336,   71,   71,   71,
      371,  371,  371,  371,  371,  344,  371,  371,  371,   71,
       71,  341,  342,  343,  345,   71,  348,   71,  371,  371,
      322,   71,  325,   71,  371,  371,  371,   71,  324,   71,
      371,   71,  371,  371,   71,   71,  371,   71,  371,   71,

      371,   71,  349,  371,  371,   71,  371,  346,  371,   71,
      371,   71,   71,  347,  371,   71,   71,   71,  371,  371,
      371,  371,   71,  371,  371,  371,  371,  371,  351,  371,
      371,  371,  350,  312,  312,  352,  312,  312,  312,  313,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      353,   71,  312,  312,  312,  312,  312,  312,   71,   71,
      371,   71,   71,   71,  348,  371,  371,  371,  371,   71,
      371,  371,  371,  371,  354,  344,  371,   71,  371,   71,
       71,   71,   71,   71,  312,  312,  371,   71,  371,  371,
      371,  371,  371,   71,   71,   71,  371,   71,   71,   71,

      371,   71,  371,  371,  371,   71,  371,  371,  371,  345,
      371,  362,  371,  371,  371,   71,  355,   71,  371,  359,
      371,  342,  343,  371,  371,   71,  371,  346,  347,   71,
      371,  354,  360,  371,  371,  371,  371,  361,  371,  356,
      371,  371,  350,  336,  336,  357,  336,  336,  336,  337,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      358,  362,  336,  336,  336,  336,  336,  336,   71,   71,
      371,   71,   71,   71,  363,  364,   71,  371,  371,  371,
      371,  371,  371,   71,   71,  371,  371,  371,  361,   71,
       71,  365,  371,  371,  336,  336,  366,   71,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  370,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  365,  371,  371,  371,  368,  367,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  370,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  369,   66,   66,   66,   66,
       68,   68,  371,   68,  182,  371,  371,  182,  314,  314,
      371,  314,  338,  338,  371,  338,  312,  312,  371,  312,
      336,  336,  371,  336,    5,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371
    } ;

static const flex_int16_t yy_chk[1464] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    4,    4,    4,   18,   18,   20,   23,   23,  374,
       27,   28,   32,   29,   30,   20,  268,   20,   20,   27,

       28,   32,   29,   30,  224,   31,   33,   36,   69,   49,
       27,   34,   68,   30,   31,   33,   36,   30,   49,   29,
       34,   30,   27,   29,   25,   32,   29,   27,   27,   33,
       30,   35,    9,   30,   28,   31,   34,   31,    5,   33,
       35,   34,   33,   37,   34,   34,    0,   31,   38,   34,
       39,   41,   37,   40,    0,   35,   50,   38,    0,   39,
       41,    0,   40,   35,    0,   50,   37,   42,    0,   43,
       37,   48,    0,   39,   41,   38,   42,   40,   43,   49,
       48,   41,   44,   39,   41,   40,   42,   41,   43,   40,
       42,   44,    0,   45,   42,   67,   43,   67,    0,   42,

       51,   44,   45,   52,   43,   44,   42,   43,   44,   51,
       50,   53,   52,   50,    0,   44,   50,   54,   44,   48,
       53,   70,   70,   45,   56,   55,   54,   72,   72,   58,
       48,   45,   63,   56,   55,   48,   48,   57,   58,    0,
       59,   63,    0,   60,   65,   74,   57,   51,   61,   59,
       81,   51,   60,   65,   74,   51,    0,   61,   73,   81,
       52,    0,   52,   51,   97,   62,   51,   73,   54,   73,
       73,   53,   52,   97,   62,    0,   56,   54,   55,   63,
       54,    0,   55,   56,   58,   55,   55,   63,   57,   64,
       55,   59,   57,    0,   63,   60,    0,   63,   64,   61,

       59,   65,   60,    0,   78,   61,   60,    0,   61,   65,
       79,   61,   62,   78,   80,    0,   62,   83,   86,   79,
       62,   82,    0,   80,   62,   84,   83,   86,   85,   88,
       82,   62,   79,    0,   84,   80,   64,   85,   88,    0,
       64,   78,   87,   64,   82,   89,   90,    0,   84,   64,
       91,   87,   64,   83,   89,   90,   86,   92,   85,   91,
       88,   93,   87,   94,   89,   85,   92,   95,    0,   96,
       93,   99,   94,   98,  101,    0,   95,   90,   96,   92,
       99,  100,   98,  101,   93,  103,    0,   91,  104,    0,
      100,  102,  105,    0,  103,   93,    0,  104,   99,   94,

      102,  105,  106,    0,  101,   95,   96,   96,  108,   98,
      102,  106,  100,  183,  107,  183,  105,  108,  109,  110,
      111,    0,  104,  107,  105,  112,  104,  109,  110,  111,
      105,  113,  114,  115,  112,  117,  107,    0,  118,  106,
      113,  114,  115,  110,  117,  116,  116,  118,    0,  108,
      108,  121,  119,    0,  113,  116,  109,  118,    0,  120,
      121,  119,  115,  122,    0,  114,  123,  117,  120,  118,
      124,  125,  122,  116,    0,  123,  118,  119,  126,  124,
      125,  120,  127,  121,  129,    0,  128,  126,  131,    0,
        0,  127,  130,  129,  125,  128,  133,  131,  123,  132,

        0,  130,    0,  122,  134,  133,  124,  125,  132,  128,
      126,  130,  135,  134,  136,  131,  137,  138,  132,  139,
      140,  135,  141,  136,  127,  137,  138,  143,  139,  140,
      142,  141,  144,  145,  146,  147,  143,  148,  149,  142,
      150,  144,  145,  146,  147,    0,  148,  149,  151,  150,
      154,    0,    0,  152,  134,  153,    0,  151,  156,  154,
      133,  135,  152,  155,  153,  136,  157,  156,  138,  158,
      141,  159,  155,  160,  143,  157,  139,    0,  158,  137,
      159,    0,  160,  139,  146,  140,  147,    0,  142,  161,
      144,    0,  162,  164,    0,    0,  147,  145,  161,    0,

      148,  162,  164,  149,  150,  150,  163,  154,  152,    0,
      155,  151,    0,  153,    0,  163,    0,  165,  157,  156,
      167,  159,    0,  156,    0,  157,  165,  166,  166,  167,
      168,  157,    0,  158,  169,    0,  170,  166,  171,  168,
      172,  160,  160,  169,  162,  170,  173,  171,    0,  172,
      174,  175,  176,  164,  161,  173,  177,  163,  178,  174,
      175,  176,  180,  179,    0,  177,  184,  178,    0,  181,
        0,  180,  179,  165,    0,  184,  185,  168,  181,  167,
      186,  187,  188,  166,  189,  185,  170,  169,  168,  186,
      187,  188,  191,  189,    0,  168,    0,  171,    0,  190,

        0,  191,  175,  189,    0,  173,  193,  172,  190,  178,
      179,  176,  192,  174,  175,  193,  181,  180,  194,  195,
      196,  192,    0,    0,  197,  177,  198,  194,  195,  196,
      199,  192,  190,  197,  200,  198,    0,  201,    0,  199,
      202,  203,    0,  200,  204,  193,  201,  197,  205,  202,
      203,  199,  206,  204,  196,  207,  208,  205,  210,  209,
      195,  206,  211,  212,  207,  208,  213,  210,  209,    0,
        0,  211,  212,  214,  215,  213,  216,  204,  207,  209,
      203,  217,  214,  215,  206,  216,  218,  219,    0,  208,
      217,  220,    0,  221,  222,  218,  219,  210,  223,  225,

      220,  212,  221,  222,  226,  227,  231,  223,  225,  230,
      232,  229,  215,  226,  227,  231,  234,    0,  230,  232,
      229,  223,  221,  219,  218,  234,  226,  227,    0,    0,
        0,  225,  222,  228,  228,  230,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      229,  233,  228,  228,  228,  228,  228,  228,  235,  236,
      233,  237,  238,  239,    0,    0,  240,  235,  236,  241,
      237,  238,  239,  242,  233,  240,    0,  243,  241,  244,
      245,    0,  242,  246,  228,  228,  243,    0,  244,  245,
      241,  247,  246,  236,  248,  249,  235,  243,  240,  251,

      247,  239,  252,  248,  249,  242,  250,  253,  251,  254,
      256,  252,  255,  259,  257,  250,  253,  258,  254,  256,
      260,  255,  259,  257,  261,  262,  258,  245,  263,  260,
      265,  264,  266,  261,  262,    0,  267,  263,  247,  265,
      264,  266,    0,  246,  269,  267,  270,  274,  271,  275,
      251,  252,    0,  269,    0,  270,  274,  271,  275,    0,
      248,  256,    0,  249,    0,  258,  273,  250,  276,  254,
        0,  255,    0,  253,  257,  273,    0,  276,    0,  259,
        0,  277,  278,  279,    0,  260,  265,  267,    0,  261,
      277,  278,  279,  263,  264,    0,  270,  266,  271,    0,

      275,  274,    0,  269,  272,  272,    0,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  280,  281,  272,  272,  272,  272,  272,  272,  282,
      280,  281,  273,  276,  283,  287,  285,  286,  282,    0,
      288,  289,  277,  283,  287,  285,  286,    0,  279,  288,
      289,  290,  291,  292,  293,  272,  272,  294,  295,  296,
      290,  291,  292,  293,    0,  288,  294,  295,  296,  297,
      298,  281,  285,  286,  293,  299,  300,  301,  297,  298,
      280,  303,  283,  304,  299,  300,  301,  305,  282,  306,
      303,  307,  304,    0,  309,  310,  305,  311,  306,  315,

      307,  317,  304,  309,  310,  318,  311,  297,  315,  319,
      317,  321,  316,  299,  318,  322,  324,  325,  319,    0,
      321,  316,  328,    0,  322,  324,  325,    0,  310,    0,
        0,  328,  309,  314,  314,  315,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      316,  323,  314,  314,  314,  314,  314,  314,  326,  327,
      323,  329,  330,  331,  332,    0,    0,  326,  327,  333,
      329,  330,  331,  332,  323,  328,    0,  334,  333,  335,
      341,  342,  339,  343,  314,  314,  334,  344,  335,  341,
      342,  339,  343,  345,  346,  340,  344,  347,  349,  350,

        0,  351,  345,  346,  340,  352,  347,  349,  350,  329,
      351,  353,    0,    0,  352,  354,  333,  356,    0,  349,
      353,  326,  327,    0,  354,  355,  356,  330,  331,  357,
        0,  341,  351,    0,  355,    0,    0,  352,  357,  335,
        0,    0,  334,  338,  338,  339,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      340,  358,  338,  338,  338,  338,  338,  338,  359,  360,
      358,  361,  363,  364,  355,  356,  365,  359,  360,    0,
      361,  363,  364,  366,  367,  365,    0,    0,  357,  368,
      369,  359,  366,  367,  338,  338,  360,  370,  368,  369,

        0,    0,    0,    0,    0,    0,  370,    0,    0,    0,
        0,    0,  368,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  363,    0,    0,    0,  366,  364,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  369,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  367,  372,  372,  372,  372,
      373,  373,    0,  373,  375,    0,    0,  375,  376,  376,
        0,  376,  377,  377,    0,  377,  378,  378,    0,  378,
      379,  379,    0,  379,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grsoft.l"

#line 889 "lex.yy.c"

#define INITIAL 0
#define exec 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 2 "grsoft.l"

#line 1109 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1385 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(exec):
#line 3 "grsoft.l"
{
	yypop_buffer_state();
        if (!YY_CURRENT_BUFFER)
		yyterminate();
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 8 "grsoft.l"
{ return PR; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "grsoft.l"
{ return STR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 10 "grsoft.l"
{ return CLEAR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 11 "grsoft.l"
{ return COLOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 12 "grsoft.l"
{ return DRAW; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 13 "grsoft.l"
{ return LIST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "grsoft.l"
{ return RUN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "grsoft.l"
{ return PRINT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "grsoft.l"
{ return INPUT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "grsoft.l"
{ return DUMP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "grsoft.l"
{ return IF; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "grsoft.l"
{ return THEN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 20 "grsoft.l"
{ return ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 21 "grsoft.l"
{ return FOR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 22 "grsoft.l"
{ return NEXT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 23 "grsoft.l"
{ return STEP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 24 "grsoft.l"
{ return TO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 25 "grsoft.l"
{ return GOTO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 26 "grsoft.l"
{ return GOSUB; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 27 "grsoft.l"
{ return RETURN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 28 "grsoft.l"
{ return NEW; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 29 "grsoft.l"
{ return TRACE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 30 "grsoft.l"
{ return NOTRACE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 31 "grsoft.l"
{ return ON; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 32 "grsoft.l"
{ return OFF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 33 "grsoft.l"
{ return HGR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 34 "grsoft.l"
{ return HPLOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 35 "grsoft.l"
{ return TEXT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 36 "grsoft.l"
{ return LEN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 37 "grsoft.l"
{ return NOT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 38 "grsoft.l"
{ return END; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 39 "grsoft.l"
{ return READ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 40 "grsoft.l"
{ return DATA; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 41 "grsoft.l"
{ return VLIN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 42 "grsoft.l"
{ return HLIN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 43 "grsoft.l"
{ return GR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 44 "grsoft.l"
{ return PLOT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 45 "grsoft.l"
{ return LET; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 46 "grsoft.l"
{ return SQR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 47 "grsoft.l"
{ return SIN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 48 "grsoft.l"
{ return COS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 49 "grsoft.l"
{ return TAN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 50 "grsoft.l"
{ return EXP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 51 "grsoft.l"
{ return RANDOMIZE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 52 "grsoft.l"
{ return DIM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 53 "grsoft.l"
{ return ABS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 54 "grsoft.l"
{ return OR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 55 "grsoft.l"
{ return AND; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 56 "grsoft.l"
{ return RND; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 57 "grsoft.l"
{ return ASC; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 58 "grsoft.l"
{ return SYSTEM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 59 "grsoft.l"
{ return MID; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 60 "grsoft.l"
{ return LEFT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 61 "grsoft.l"
{ return RIGHT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 62 "grsoft.l"
{ return CHR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 63 "grsoft.l"
{ return HTAB; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 64 "grsoft.l"
{ return VTAB; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 65 "grsoft.l"
{ return HOME; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 66 "grsoft.l"
{ return PEEK; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 67 "grsoft.l"
{ return POKE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 68 "grsoft.l"
{ return GET; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 69 "grsoft.l"
{ return AT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 70 "grsoft.l"
{ return SAVE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 71 "grsoft.l"
{ return DEBUG; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 72 "grsoft.l"
{ return INT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 73 "grsoft.l"
BEGIN(exec);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 74 "grsoft.l"

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 75 "grsoft.l"
{
	yyin=fopen(yytext,"r");
	if (!yyin) {
		fprintf(stderr,"error opening %s\n",yytext);
	} else {
	yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
	BEGIN(INITIAL);
	}
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "grsoft.l"
{ return REM; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "grsoft.l"
{ yylval=atof(yytext);return NUMBER; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "grsoft.l"
{ yylval=atof(yytext);return FLOAT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "grsoft.l"
{ return QUOTE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "grsoft.l"
{ strcpy(identifier,yytext); return IDENTIFIER;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "grsoft.l"
{ strcpy(identifier,yytext); return STRING;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "grsoft.l"
{ return GE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "grsoft.l"
{ return PE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "grsoft.l"
{ return EQUAL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "grsoft.l"
{ return CO; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "grsoft.l"
{ return CF; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "grsoft.l"
{ return PO; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "grsoft.l"
{ return PF; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "grsoft.l"
{ return DP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "grsoft.l"
{ return PG; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "grsoft.l"
{ return PP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "grsoft.l"
{ return DIFF; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "grsoft.l"
{ return MOD; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "grsoft.l"
{ return MINUS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "grsoft.l"
{ return PLUS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "grsoft.l"
{ return ASTERISK; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 105 "grsoft.l"
{ return DIVIDE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "grsoft.l"
{ return DOT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "grsoft.l"
{ return COMMA; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "grsoft.l"
{ return SEMICOLOMN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "grsoft.l"
{ return AMPER; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 110 "grsoft.l"
{ ll++; return CR; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "grsoft.l"
{}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "grsoft.l"
{ strcpy(chars,yytext); strcpy(string,yytext+1); string[strlen(yytext)-2]=0; return CHARS; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "grsoft.l"
ECHO;
	YY_BREAK
#line 1674 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 371);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 113 "grsoft.l"


