
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[356] =
    {   0,
        0,    0,   64,   64,   94,   93,   90,   91,   69,   81,
       89,   75,   76,   84,   83,   87,   82,   86,   85,   67,
       77,   88,   79,   72,   78,    6,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   73,   74,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   65,   64,    0,   92,   68,
       71,    0,   67,   70,   80,   70,   70,   70,   59,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   33,   70,   70,   70,   70,   70,

        9,   70,   70,   70,   70,   70,   70,   70,   21,   44,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   15,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   65,
       64,   43,   45,   47,   48,   70,   70,   70,   38,   70,
       70,   42,   70,   70,   70,   28,   70,   40,   12,   58,

       70,   70,   23,   70,   70,   70,   70,   70,   62,   70,
       26,   35,   70,   70,   19,   70,   27,   22,   70,   70,
       70,   70,   70,   70,   66,   70,   70,   46,    5,   70,
       37,   70,   70,   39,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   66,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   52,   70,   70,   30,
       70,    3,    8,   11,   63,   70,   16,   32,   55,   70,
       53,   70,   70,    4,   49,   13,   56,   34,   57,   70,

       70,   29,   66,   66,   66,   70,   70,   60,   36,   14,
       25,   10,   70,   31,   54,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   66,   66,   66,   70,   70,   70,
        1,    2,   61,   17,   24,    7,   50,    6,   70,   70,
       70,   20,   70,   70,   70,   70,   18,   51,   70,   70,
       70,   70,   70,   41,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    1,   51,    1,   33,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   33,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   76,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    2,    3,    2,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    4,    1,    1,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[364] =
    {   0,
        0,    0,   75,   78,  153, 1315, 1315, 1315,  144, 1315,
     1315, 1315, 1315, 1315, 1315, 1315, 1315,  131, 1315,   77,
     1315, 1315,  110, 1315, 1315, 1315,   78,   80,   81,   82,
       92,   84,   96,  103,  125,   85,  129,   98,  130,  137,
      141,  149,  165,  179,  157, 1315, 1315,  145,  144,  169,
      181,  184,  102,  189,  206,  196,  207,  210,  217,  220,
      224,  223,  241,  244,  236,    0,  293,  120,  100,   84,
     1315,   72,  298,  212, 1315,  263,  275,  259,  301,  304,
      308,  311,  312,  314,  315,  316,  318,  319,  322,  329,
      330,  335,  345,  347,  353,  355,  359,  357,  360,  377,

      365,  367,  371,  379,  372,  392,  397,  396,  398,  403,
      409,  411,  413,  414,  416,  421,  426,  427,  428,  429,
      444,  445,  452,  446,  456,  457,  460,  463,  462,  464,
      467,  478,  483,  484,  485,  486,  489,  490,  491,  496,
      502,  501,  503,  506,  507,  508,  504,  509,  514,  520,
      524,  519,  532,  526,  537,  540,  542,  550,  556,  560,
      562,  580,  583,  587,  584,  597,  585,  598,  599,  600,
      604,  605,  610,  615,  616,  621,  622,  623,  626,    0,
      344,  627,  640,  644,  646,  650,  656,  669,  670,  676,
      680,  681,  682,  683,  686,  687,  693,  688,  698,  700,

      703,  705,  706,  711,  710,  717,  721,  724,  725,  727,
      729,  735,  739,  743,  745,  746,  747,  750,  751,  757,
      758,  761,  763,  765,  800,  773,  768,  769,  781,  818,
      788,  819,  820,  821,  822,  823,  826,  824,  838,  825,
      839,  841,  842,  843,  849,  860,  861,  862,  863,  864,
      866,  865,  867,  878,  868,  880,  881,  882,  883,  884,
      886,  896,  894,  904,  909,  964,  921,  898,  932,  897,
      927,  929,  931,  948,  934,  975, 1315,  985,  988,  990,
      991,  995,  998, 1001, 1002, 1005, 1003, 1016, 1017, 1018,
     1019, 1021, 1029, 1031, 1315, 1032, 1033, 1034, 1035, 1036,

     1037, 1039,    0,    0, 1079, 1062, 1061, 1047, 1050, 1051,
     1054, 1057, 1090, 1067, 1100, 1101, 1102, 1104, 1105, 1106,
     1107, 1108, 1118, 1119,    0,    0, 1188, 1137, 1121, 1122,
     1120, 1125, 1126, 1132, 1133, 1136, 1315, 1138, 1139, 1144,
     1140, 1150, 1151, 1157, 1158, 1209, 1165, 1315, 1168, 1207,
     1210, 1212, 1211, 1214, 1315, 1286, 1290,   81, 1294, 1298,
     1302, 1306, 1310
    } ;

static const flex_int16_t yy_def[364] =
    {   0,
      355,    1,  356,  356,  355,  355,  355,  355,  357,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  358,
      355,  355,  355,  355,  355,  355,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  355,  355,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  359,  355,  357,  357,  355,
      355,  355,  358,  358,  355,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  359,
      355,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  360,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  361,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  355,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  355,  358,  358,  358,  358,  358,

      358,  358,  362,  362,  360,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  363,  363,  361,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  355,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  355,  358,  358,
      358,  358,  358,  358,    0,  355,  355,  355,  355,  355,
      355,  355,  355
    } ;

static const flex_int16_t yy_nxt[1392] =
    {   0,
        6,    6,    7,    8,    9,    6,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   36,   37,   38,   39,   40,   41,   36,
       42,   43,   44,   36,   45,   36,   36,   36,   36,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       36,   57,   58,   59,   60,   61,   36,   62,   63,   64,
       36,   65,   36,   36,   36,   36,   67,    6,   67,   67,
        6,   67,   71,   71,   74,   71,   71,   71,   70,   71,
       71,   72,  355,   73,  355,  355,  355,   71,  355,  355,

       70,   71,   76,   71,   69,   84,  355,   71,   71,   85,
      355,   81,  355,   86,   77,   82,  355,  355,   83,   78,
       79,   92,   87,   93,   69,   88,   89,   80,   90,  105,
       71,   75,   96,   94,   71,   71,   95,   97,   91,  355,
       98,   99,   71,  355,  355,  100,   71,   70,   69,   71,
       71,  355,  355,  101,   71,  355,  103,  106,  355,  355,
      104,  102,   71,  355,  355,  108,  146,  107,  111,  355,
       71,  355,  115,  109,   71,  112,  116,  110,  113,  355,
      117,  114,  355,  355,   71,  118,   71,  355,  120,   71,
      355,  129,  119,  355,   71,  355,  121,  131,  355,  130,

      355,   71,  124,  355,  122,  355,  125,  123,  132,  126,
      355,   71,   71,  133,   79,   71,  127,   71,  134,  128,
      355,  355,   71,  355,  355,   71,  355,  135,   71,   71,
      136,  355,  138,  137,  355,  355,  139,  355,  355,  355,
      140,   71,  355,  355,  147,  143,   71,  144,  141,   71,
      355,  142,  101,  148,  355,  355,   95,  145,  355,  154,
      355,  355,  155,  149,   71,  355,  156,  150,   71,  157,
      151,  152,  158,  355,  165,  153,  160,  355,  166,  161,
       71,  159,  167,  109,  184,  162,  168,  110,  163,  355,
      355,  164,  170,  169,  181,  174,  181,  178,  355,  175,

      171,  183,  176,   71,  182,  179,   71,  172,  127,   71,
      173,  177,   72,   71,   73,  355,   71,   71,  355,   71,
       71,   71,  355,   71,   71,  355,  355,   71,  355,  355,
      355,  185,  355,  355,   71,   71,  355,  355,  187,  191,
       71,  193,  355,  355,  355,  181,  188,  181,  186,  355,
       71,  192,   71,  189,  194,  196,  190,  197,   71,  355,
       71,  355,   71,  195,   71,   71,  355,  355,  198,  355,
       71,  355,   71,  355,  355,  199,   71,   71,  355,  355,
      355,  355,   71,  355,   71,  355,  355,  200,  201,  202,
      204,  355,  205,  355,  206,  203,  355,   71,  214,  210,

      207,   71,   71,   71,  355,  208,  355,  211,   71,  209,
      355,  355,  355,  212,   71,  355,   71,  355,   71,   71,
      213,   71,  355,  355,  218,  355,   71,  355,  355,  355,
      355,   71,   71,   71,   71,  355,  219,  215,  216,  217,
      355,  355,  355,  355,  224,  222,  221,  355,  220,   71,
       71,   71,  223,  228,  355,  227,  225,   71,  355,  355,
      355,   71,   71,  226,  229,   71,  355,   71,   71,   71,
      355,  355,   71,  230,  355,  355,  355,  355,  355,  233,
      231,  355,  234,   71,  236,  232,  237,  239,   71,   71,
       71,   71,  355,  238,   71,   71,   71,  355,  355,  355,

      355,   71,  235,  355,  355,  355,   71,   71,   71,   71,
      355,   71,   71,   71,   71,  355,  355,  355,  355,   71,
      355,  355,  355,  355,   71,   71,  355,  355,  355,   71,
      355,   71,  183,  355,  355,  182,  184,   71,  355,  185,
      355,  241,   71,  244,  355,   71,  355,   71,  355,  355,
      242,  355,  240,  245,  355,   71,  355,  189,  192,  243,
      196,   71,  248,  246,  355,   71,  355,   71,  355,  355,
      355,  247,  198,  200,  355,  199,  355,  249,  250,  251,
      253,  203,  355,  254,  355,   71,  252,  355,   71,   71,
       71,  255,   71,  256,  355,  209,  258,  355,  355,  355,

      211,  355,   71,   71,   71,   71,  212,  355,  257,   71,
       71,  355,  355,  355,  355,   71,  218,  260,  355,  355,
       71,   71,  215,  259,  355,  217,   71,   71,   71,  355,
      355,   71,   71,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  268,  262,  261,   71,  263,  264,  265,   71,
      355,   71,  228,  355,  355,  277,  355,  355,  355,  266,
      355,   71,  229,  355,  355,  271,  267,  231,  355,  355,
      355,  269,  270,  274,   71,   71,  273,  276,  234,  278,
      355,   71,  275,  355,  355,   71,   71,   71,   71,  272,
      355,   71,   71,   71,  355,  355,  355,  355,   71,  280,

      355,  355,  355,   71,  355,   71,  279,  355,   71,  355,
       71,   71,  355,  284,  355,   71,   71,  355,  285,  355,
      355,  283,   71,  281,  355,  355,   71,  282,  355,   71,
       71,  355,   71,  355,   71,  355,  355,  289,  355,  355,
       71,  355,  287,  355,   71,  291,  286,  288,  295,  355,
       71,   71,   71,  355,  290,   71,   71,  355,  355,  355,
      355,  355,   71,   71,  355,  355,   71,  292,   71,  293,
       71,  355,  355,   71,   71,  355,  355,  355,   71,  355,
      355,  294,  355,  355,  297,  299,   71,  355,  296,  301,
      355,  302,  355,   71,  355,  355,  355,  300,  307,  298,

      303,  303,  355,  303,  303,  304,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  306,  303,  303,  303,
      303,  303,  303,   71,   71,   71,   71,   71,   71,   71,
      277,   71,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,   71,   71,  308,   71,   71,   71,  303,
      303,  313,  355,  355,   71,  355,  355,  355,  310,  312,
      314,  309,  315,  355,  311,   71,   71,   71,   71,   71,
       71,   71,   71,   71,  355,  355,  355,  355,  355,  355,
      355,  355,  355,   71,  355,   71,   71,  295,   71,   71,
      316,   71,  355,  280,  355,  355,  355,  355,  355,   71,

      355,   71,   71,   71,  355,  317,  355,  355,  355,   71,
      355,  355,  355,  318,   71,  285,  284,  355,  355,  355,
      289,  282,  355,  355,  355,  283,   71,  355,  287,  288,
      291,  320,   71,  319,   71,  355,   71,   71,  321,   71,
      355,  355,  355,  355,  297,  355,  355,  355,  355,  322,
      294,  299,  296,   71,  355,  298,  329,  323,  324,  355,
      355,  355,  355,  302,  325,  325,  309,  325,  325,  326,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
       71,  325,  325,  325,  325,  325,  325,  308,  355,  355,
       71,  328,  310,   71,  312,   71,   71,  314,  311,  355,

       71,  330,  355,   71,  355,  355,   71,   71,   71,  355,
       71,  355,  355,  325,  325,  355,  355,  355,  355,  355,
      333,   71,   71,   71,   71,  331,   71,  315,  332,  334,
      355,  355,  355,  355,  337,  355,   71,   71,   71,   71,
       71,   71,   71,  355,   71,  355,  355,  355,  355,  355,
      355,  355,   71,  355,  355,   71,   71,  355,  355,   71,
      335,  355,   71,  336,  355,  355,   71,   71,  355,  355,
      355,  355,   71,  355,  339,  355,  355,  355,  338,  303,
      303,  355,  303,  303,  304,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,   71,  303,  303,  303,  303,

      303,  303,  340,  341,  355,   71,   71,   71,  355,   71,
       71,   71,   71,  337,  355,  355,  355,  342,  355,  355,
      355,  355,  355,   71,   71,   71,   71,   71,  303,  303,
       71,   71,  355,  355,  355,  355,  355,   71,   71,  355,
      355,   71,   71,   71,   71,  348,  355,  355,  355,   71,
      355,  355,  355,  355,  355,   71,   71,  334,  355,  355,
      355,  333,   71,  348,  355,  355,  355,  355,  331,  332,
       71,  355,  355,   71,  346,  335,  336,  342,  355,  355,
      347,  355,  355,  343,  355,  355,  355,  338,  325,  325,
      345,  325,  325,  326,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  344,  325,  325,  325,  325,  325,
      325,  355,   71,  349,   71,   71,   71,   71,  355,   71,
      347,  355,  355,  355,  355,  355,  355,  351,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  325,  325,  354,
      350,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  352,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  354,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  353,   66,   66,   66,   66,
       68,   68,  355,   68,  180,  355,  355,  180,  305,  305,

      355,  305,  327,  327,  355,  327,  303,  303,  355,  303,
      325,  325,  355,  325,    5,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355

    } ;

static const flex_int16_t yy_chk[1392] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    4,
        4,    4,   20,   27,  358,   28,   29,   30,   72,   32,
       36,   20,   27,   20,   28,   29,   30,   31,   32,   36,

       70,   33,   27,   38,   69,   30,   31,   53,   34,   30,
       33,   29,   38,   30,   27,   29,   53,   34,   29,   27,
       27,   32,   30,   33,   68,   30,   31,   28,   31,   38,
       35,   23,   34,   33,   37,   39,   33,   34,   31,   35,
       34,   34,   40,   37,   39,   34,   41,   18,    9,   49,
       48,   40,    5,   35,   42,   41,   37,   39,   49,   48,
       37,   35,   45,   42,    0,   40,   53,   39,   41,    0,
       43,   45,   42,   40,   50,   41,   42,   40,   41,   43,
       42,   41,    0,   50,   44,   42,   51,    0,   43,   52,
        0,   45,   42,   44,   54,   51,   43,   48,   52,   45,

        0,   56,   44,   54,   43,    0,   44,   43,   48,   44,
       56,   55,   57,   48,   48,   58,   44,   74,   49,   44,
       55,   57,   59,    0,   58,   60,   74,   50,   62,   61,
       50,   59,   51,   50,   60,    0,   51,   62,   61,    0,
       51,   65,    0,    0,   54,   52,   63,   52,   51,   64,
       65,   51,   56,   54,    0,   63,   54,   52,   64,   56,
        0,    0,   57,   55,   78,    0,   57,   55,   76,   58,
       55,   55,   59,   78,   62,   55,   60,   76,   62,   61,
       77,   59,   62,   60,   78,   61,   62,   60,   61,   77,
        0,   61,   63,   62,   67,   64,   67,   65,    0,   64,

       63,   77,   64,   73,   76,   65,   79,   63,   64,   80,
       63,   64,   73,   81,   73,   79,   82,   83,   80,   84,
       85,   86,   81,   87,   88,   82,   83,   89,   84,   85,
       86,   80,   87,   88,   90,   91,   89,    0,   82,   85,
       92,   87,    0,   90,   91,  181,   83,  181,   81,   92,
       93,   86,   94,   83,   88,   90,   84,   91,   95,   93,
       96,   94,   98,   89,   97,   99,    0,   95,   91,   96,
      101,   98,  102,   97,   99,   92,  103,  105,    0,  101,
        0,  102,  100,    0,  104,  103,  105,   93,   94,   94,
       97,  100,   98,  104,   99,   96,    0,  106,  105,  103,

      100,  108,  107,  109,    0,  102,  106,  103,  110,  102,
      108,  107,  109,  103,  111,    0,  112,  110,  113,  114,
      104,  115,    0,  111,  108,  112,  116,  113,  114,    0,
      115,  117,  118,  119,  120,  116,  111,  106,  106,  107,
      117,  118,  119,  120,  116,  114,  113,    0,  112,  121,
      122,  124,  115,  118,    0,  117,  116,  123,  121,  122,
      124,  125,  126,  116,  119,  127,  123,  129,  128,  130,
      125,  126,  131,  120,  127,    0,  129,  128,  130,  123,
      121,  131,  124,  132,  126,  122,  128,  130,  133,  134,
      135,  136,  132,  129,  137,  138,  139,  133,  134,  135,

      136,  140,  125,  137,  138,  139,  142,  141,  143,  147,
      140,  144,  145,  146,  148,  142,  141,  143,  147,  149,
      144,  145,  146,  148,  152,  150,    0,    0,  149,  151,
        0,  154,  132,  152,  150,  131,  133,  153,  151,  134,
      154,  136,  155,  139,    0,  156,  153,  157,    0,    0,
      137,  155,  135,  141,  156,  158,  157,  137,  140,  138,
      144,  159,  145,  142,  158,  160,    0,  161,    0,    0,
      159,  143,  145,  147,  160,  146,  161,  148,  148,  150,
      152,  149,    0,  153,    0,  162,  151,    0,  163,  165,
      167,  154,  164,  155,  162,  154,  157,  163,  165,  167,

      155,  164,  166,  168,  169,  170,  155,    0,  156,  171,
      172,  166,  168,  169,  170,  173,  160,  161,  171,  172,
      174,  175,  158,  158,  173,  159,  176,  177,  178,  174,
      175,  179,  182,    0,    0,  176,  177,  178,    0,    0,
      179,  182,  167,  163,  162,  183,  164,  165,  166,  184,
        0,  185,  168,    0,  183,  186,    0,    0,  184,  166,
      185,  187,  169,    0,  186,  173,  166,  171,    0,    0,
      187,  170,  172,  177,  188,  189,  176,  179,  174,  187,
        0,  190,  178,  188,  189,  191,  192,  193,  194,  175,
      190,  195,  196,  198,  191,  192,  193,  194,  197,  190,

      195,  196,  198,  199,    0,  200,  188,  197,  201,    0,
      202,  203,  199,  195,  200,  205,  204,  201,  197,  202,
      203,  194,  206,  191,  205,  204,  207,  193,    0,  208,
      209,  206,  210,    0,  211,  207,    0,  205,  208,  209,
      212,  210,  202,  211,  213,  207,  201,  204,  214,  212,
      215,  216,  217,  213,  206,  218,  219,  214,    0,  215,
      216,  217,  220,  221,  218,  219,  222,  208,  223,  210,
      224,  220,  221,  227,  228,  222,    0,  223,  226,  224,
        0,  213,  227,  228,  219,  221,  229,  226,  216,  223,
        0,  224,    0,  231,    0,  229,    0,  222,  227,  220,

      225,  225,  231,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  226,  225,  225,  225,
      225,  225,  225,  230,  232,  233,  234,  235,  236,  238,
      240,  237,  230,  232,  233,  234,  235,  236,  238,  240,
      237,    0,    0,  239,  241,  230,  242,  243,  244,  225,
      225,  237,  239,  241,  245,  242,  243,  244,  233,  236,
      238,  232,  239,  245,  235,  246,  247,  248,  249,  250,
      252,  251,  253,  255,  246,  247,  248,  249,  250,  252,
      251,  253,  255,  254,    0,  256,  257,  258,  259,  260,
      241,  261,  254,  243,  256,  257,  258,  259,  260,  263,

      261,  262,  270,  268,    0,  242,    0,    0,  263,  264,
      262,  270,  268,  244,  265,  248,  247,    0,  264,    0,
      252,  245,    0,  265,    0,  246,  267,    0,  250,  251,
      254,  253,  271,  249,  272,  267,  273,  269,  255,  275,
        0,  271,    0,  272,  260,  273,  269,    0,  275,  256,
      257,  262,  259,  274,    0,  261,  268,  263,  264,    0,
        0,    0,  274,  265,  266,  266,  270,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      276,  266,  266,  266,  266,  266,  266,  269,    0,  276,
      278,  267,  271,  279,  273,  280,  281,  275,  272,  278,

      282,  274,  279,  283,  280,  281,  284,  285,  287,  282,
      286,    0,  283,  266,  266,  284,  285,  287,    0,  286,
      281,  288,  289,  290,  291,  278,  292,  276,  279,  286,
      288,  289,  290,  291,  293,  292,  294,  296,  297,  298,
      299,  300,  301,  293,  302,  294,  296,  297,  298,  299,
      300,  301,  308,  302,    0,  309,  310,    0,    0,  311,
      290,  308,  312,  292,  309,  310,  307,  306,  311,    0,
        0,  312,  314,    0,  301,  307,  306,    0,  300,  305,
      305,  314,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  313,  305,  305,  305,  305,

      305,  305,  306,  307,  313,  315,  316,  317,    0,  318,
      319,  320,  321,  322,  315,  316,  317,  313,  318,  319,
      320,  321,  322,  323,  324,  331,  329,  330,  305,  305,
      332,  333,  323,  324,  331,  329,  330,  334,  335,  332,
      333,  336,  328,  338,  339,  341,  334,  335,    0,  340,
      336,  328,  338,  339,  341,  342,  343,  319,  340,    0,
        0,  318,  344,  345,  342,  343,    0,    0,  316,  317,
      347,  344,  345,  349,  339,  320,  321,  330,    0,  347,
      340,    0,  349,  324,    0,    0,    0,  323,  327,  327,
      329,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  328,  327,  327,  327,  327,  327,
      327,    0,  350,  343,  346,  351,  353,  352,    0,  354,
      344,  350,    0,  346,  351,  353,  352,  349,  354,    0,
        0,    0,    0,    0,    0,    0,    0,  327,  327,  352,
      346,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  350,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  353,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  351,  356,  356,  356,  356,
      357,  357,    0,  357,  359,    0,    0,  359,  360,  360,

        0,  360,  361,  361,    0,  361,  362,  362,    0,  362,
      363,  363,    0,  363,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grsoft.l"

#line 871 "lex.yy.c"

#define INITIAL 0
#define exec 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 2 "grsoft.l"

#line 1091 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1315 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(exec):
#line 3 "grsoft.l"
{
	yypop_buffer_state();
        if (!YY_CURRENT_BUFFER)
		yyterminate();
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 8 "grsoft.l"
{ return CLEAR; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "grsoft.l"
{ return COLOR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 10 "grsoft.l"
{ return DRAW; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 11 "grsoft.l"
{ return LIST; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 12 "grsoft.l"
{ return RUN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 13 "grsoft.l"
{ return PRINT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "grsoft.l"
{ return INPUT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "grsoft.l"
{ return DUMP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "grsoft.l"
{ return IF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "grsoft.l"
{ return THEN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "grsoft.l"
{ return ELSE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "grsoft.l"
{ return FOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 20 "grsoft.l"
{ return NEXT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 21 "grsoft.l"
{ return STEP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 22 "grsoft.l"
{ return TO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 23 "grsoft.l"
{ return GOTO; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 24 "grsoft.l"
{ return GOSUB; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 25 "grsoft.l"
{ return RETURN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 26 "grsoft.l"
{ return NEW; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 27 "grsoft.l"
{ return TRACE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 28 "grsoft.l"
{ return ON; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 29 "grsoft.l"
{ return OFF; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 30 "grsoft.l"
{ return HGR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 31 "grsoft.l"
{ return HPLOT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 32 "grsoft.l"
{ return TEXT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 33 "grsoft.l"
{ return LEN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 34 "grsoft.l"
{ return NOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 35 "grsoft.l"
{ return END; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 36 "grsoft.l"
{ return READ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 37 "grsoft.l"
{ return DATA; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 38 "grsoft.l"
{ return VLIN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 39 "grsoft.l"
{ return HLIN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 40 "grsoft.l"
{ return GR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 41 "grsoft.l"
{ return PLOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 42 "grsoft.l"
{ return LET; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 43 "grsoft.l"
{ return SQR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 44 "grsoft.l"
{ return SIN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 45 "grsoft.l"
{ return COS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 46 "grsoft.l"
{ return TAN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 47 "grsoft.l"
{ return EXP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 48 "grsoft.l"
{ return RANDOMIZE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 49 "grsoft.l"
{ return DIM; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 50 "grsoft.l"
{ return ABS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 51 "grsoft.l"
{ return OR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 52 "grsoft.l"
{ return AND; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 53 "grsoft.l"
{ return RND; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 54 "grsoft.l"
{ return ASC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 55 "grsoft.l"
{ return SYSTEM; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 56 "grsoft.l"
{ return MID; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 57 "grsoft.l"
{ return LEFT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 58 "grsoft.l"
{ return RIGHT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 59 "grsoft.l"
{ return CHR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 60 "grsoft.l"
{ return HTAB; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 61 "grsoft.l"
{ return VTAB; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 62 "grsoft.l"
{ return HOME; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 63 "grsoft.l"
{ return PEEK; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 64 "grsoft.l"
{ return POKE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 65 "grsoft.l"
{ return GET; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 66 "grsoft.l"
{ return AT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 67 "grsoft.l"
{ return SAVE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 68 "grsoft.l"
{ return DEBUG; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 69 "grsoft.l"
{ return INT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 70 "grsoft.l"
BEGIN(exec);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 71 "grsoft.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 72 "grsoft.l"
{
	yyin=fopen(yytext,"r");
	if (!yyin) {
		fprintf(stderr,"error opening %s\n",yytext);
	} else {
	yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
	BEGIN(INITIAL);
	}
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "grsoft.l"
{ return REM; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "grsoft.l"
{ yylval=atof(yytext);return NUMBER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "grsoft.l"
{ yylval=atof(yytext);return FLOAT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "grsoft.l"
{ return QUOTE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "grsoft.l"
{ strcpy(identifier,yytext); return IDENTIFIER;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "grsoft.l"
{ strcpy(identifier,yytext); return STRING;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "grsoft.l"
{ return EQUAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "grsoft.l"
{ return CO; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "grsoft.l"
{ return CF; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "grsoft.l"
{ return PO; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "grsoft.l"
{ return PF; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "grsoft.l"
{ return DP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "grsoft.l"
{ return PG; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "grsoft.l"
{ return PP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "grsoft.l"
{ return DIFF; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "grsoft.l"
{ return MOD; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "grsoft.l"
{ return MINUS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "grsoft.l"
{ return PLUS; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "grsoft.l"
{ return ASTERISK; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 100 "grsoft.l"
{ return DIVIDE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "grsoft.l"
{ return DOT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "grsoft.l"
{ return COMMA; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 103 "grsoft.l"
{ return SEMICOLOMN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 104 "grsoft.l"
{ return AMPER; }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 105 "grsoft.l"
{ ll++; return CR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 106 "grsoft.l"
{}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 107 "grsoft.l"
{ strcpy(chars,yytext); strcpy(string,yytext+1); string[strlen(yytext)-2]=0; return CHARS; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 108 "grsoft.l"
ECHO;
	YY_BREAK
#line 1631 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 355);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 108 "grsoft.l"


